services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=forum'
      - 'POSTGRES_USER=forum_user'
      - 'POSTGRES_PASSWORD=forum_password'
    ports:
      - "5432:5432"
    volumes:
      - postgres_forum_data:/var/lib/postgresql/data
    networks:
      - forum-net

  forum:
    container_name: forum-backend
    image: 'lucasferraz95/forum-backend:1.0.0'
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/forum
    ports:
      - "8080:8080"
    networks:
      - forum-net
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_forum_data:
    driver: local

networks:
  forum-net:

