services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=forum'
      - 'POSTGRES_USER=forum_user'
      - 'POSTGRES_PASSWORD=forum_password'
    ports:
      - "5432:5432"
    volumes:
      - postgres_forum_data:/var/lib/postgresql/data
    networks:
      - forum-net

  forum:
    container_name: forum-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/forum
      - SHOW_SQL=false
    ports:
      - "8080:8080"
    networks:
      - forum-net
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_forum_data:
    driver: local

networks:
  forum-net:

